<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="6391" started-at="2020-11-17T17:28:13Z" finished-at="2020-11-17T17:28:20Z">
    <groups>
    </groups>
    <test name="Swagger Smoke Test" duration-ms="6391" started-at="2020-11-17T17:28:13Z" finished-at="2020-11-17T17:28:20Z">
      <class name="TestModels.TestPet">
        <test-method status="PASS" signature="init(org.testng.ITestContext)[pri:0, instance:TestModels.TestPet@2aafb23c]" name="init" is-config="true" duration-ms="184" started-at="2020-11-17T20:28:13Z" finished-at="2020-11-17T20:28:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@51a06cbe]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="addPet()[pri:0, instance:TestModels.TestPet@2aafb23c]" name="addPet" duration-ms="3457" started-at="2020-11-17T20:28:13Z" finished-at="2020-11-17T20:28:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addPet -->
        <test-method status="FAIL" signature="deletePet()[pri:0, instance:TestModels.TestPet@2aafb23c]" name="deletePet" duration-ms="909" started-at="2020-11-17T20:28:17Z" finished-at="2020-11-17T20:28:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at TestModels.TestPet.deletePet(TestPet.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deletePet -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:TestModels.TestPet@2aafb23c]" name="getResult" is-config="true" duration-ms="0" started-at="2020-11-17T20:28:17Z" finished-at="2020-11-17T20:28:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addPet status=SUCCESS method=TestPet.addPet()[pri:0, instance:TestModels.TestPet@2aafb23c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:TestModels.TestPet@2aafb23c]" name="getResult" is-config="true" duration-ms="12" started-at="2020-11-17T20:28:18Z" finished-at="2020-11-17T20:28:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=deletePet status=FAILURE method=TestPet.deletePet()[pri:0, instance:TestModels.TestPet@2aafb23c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="findPet()[pri:0, instance:TestModels.TestPet@2aafb23c]" name="findPet" duration-ms="967" started-at="2020-11-17T20:28:18Z" finished-at="2020-11-17T20:28:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findPet -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:TestModels.TestPet@2aafb23c]" name="getResult" is-config="true" duration-ms="34" started-at="2020-11-17T20:28:19Z" finished-at="2020-11-17T20:28:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=findPet status=SUCCESS method=TestPet.findPet()[pri:0, instance:TestModels.TestPet@2aafb23c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="updatePet()[pri:0, instance:TestModels.TestPet@2aafb23c]" name="updatePet" duration-ms="963" started-at="2020-11-17T20:28:19Z" finished-at="2020-11-17T20:28:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [405]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [405]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at TestModels.TestPet.updatePet(TestPet.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updatePet -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:TestModels.TestPet@2aafb23c]" name="getResult" is-config="true" duration-ms="8" started-at="2020-11-17T20:28:20Z" finished-at="2020-11-17T20:28:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=updatePet status=FAILURE method=TestPet.updatePet()[pri:0, instance:TestModels.TestPet@2aafb23c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="end()[pri:0, instance:TestModels.TestPet@2aafb23c]" name="end" is-config="true" duration-ms="369" started-at="2020-11-17T20:28:20Z" finished-at="2020-11-17T20:28:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- TestModels.TestPet -->
    </test> <!-- Swagger Smoke Test -->
  </suite> <!-- Suite -->
</testng-results>
